// SPDX-License-Identifier: MIT

// smscounter provides an example of generating output similar to that
// generated by github.com/danxexe/sms-counter.
//
// This is non-optimal as it encodes the required Submit TPDUs, and calculates
// the output from them rather than just performing the minimal calculations
// required for the output. OTOH CPU is cheap so I've not bothered to add
// suitably optimised methods to the library. YMMV.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/gomaja/go-sms"
	"github.com/gomaja/go-sms/encoding/gsm7/charset"
	"github.com/gomaja/go-sms/encoding/tpdu"
)

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

// run counts the message given by the arguments, writes the count to stdout,
// and returns the exit status: 0 on success, 1 if the message cannot be
// encoded, and 2 if the arguments are not valid.
func run(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("smscounter", flag.ContinueOnError)
	fs.SetOutput(stderr)
	msg := fs.String("message", "", "The message to encode")
	nli := fs.Int("language", 0, fmt.Sprintf(
		"The NLI of a character set to use in addition to the default, from %d to %d",
		charset.Start, charset.End-1))
	fs.Usage = func() { usage(fs) }
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if *msg == "" || fs.NArg() != 0 {
		fs.Usage()
		return 2
	}
	c, err := NewCount(*msg, *nli)
	if errors.Is(err, errInvalidLanguage) {
		warnf(stderr, "%v", err)
		return 2
	}
	if err != nil {
		warnf(stderr, "%v", err)
		return 1
	}
	if _, err := fmt.Fprint(stdout, c); err != nil {
		warnf(stderr, "%v", err)
		return 1
	}
	return 0
}

// warnf writes a diagnostic to stderr, where a failed write can be reported
// nowhere else.
func warnf(stderr io.Writer, format string, args ...interface{}) {
	_, _ = fmt.Fprintf(stderr, "smscounter: "+format+"\n", args...)
}

// errInvalidLanguage indicates an NLI that identifies no national language
// table, as 3GPP TS 23.038 Section 6.2.1.2.4 defines them from 1 to 13.
var errInvalidLanguage = errors.New("invalid language")

// NewCount creates the SMS count statistics for a message.
//
// The nli is 0, for the default character set only, or the National Language
// Identifier of a character set to use in addition to it.
func NewCount(msg string, nli int) (Count, error) {
	c := Count{}
	options := []sms.EncoderOption(nil)
	switch {
	case nli == 0:
	case nli >= charset.Start && nli < charset.End:
		options = append(options, sms.WithCharset(nli))
	default:
		return c, fmt.Errorf("%w %d: the NLI must be from %d to %d",
			errInvalidLanguage, nli, charset.Start, charset.End-1)
	}
	pdus, err := sms.Encode([]byte(msg), options...)
	if err != nil {
		return c, err
	}
	alpha := pdus[0].Alphabet()
	// The UD is septets for 7bit, as it is unpacked, and octets otherwise,
	// two for each UCS-2 code unit.
	unit := 1
	switch alpha {
	case tpdu.Alpha7Bit:
		if hasEscapes(pdus) {
			c.Encoding = "7BIT_EX"
		} else {
			c.Encoding = "7BIT"
		}
	case tpdu.Alpha8Bit:
		c.Encoding = "8BIT"
	case tpdu.AlphaUCS2:
		c.Encoding = "UCS-2"
		unit = 2
	}
	c.Pdulen = pdus[0].UDBlockSize() / unit
	c.Llen = len(pdus[len(pdus)-1].UD) / unit
	c.Remaining = c.Pdulen - c.Llen
	c.Messages = len(pdus)
	// A segment may be a unit short of the block size, as an escape sequence
	// or a UTF-16 surrogate pair is not split between segments (3GPP TS
	// 23.040 Section 9.2.3.24.1), so the total is counted segment by segment.
	for _, p := range pdus {
		c.Tlen += len(p.UD) / unit
	}
	return c, nil
}

func hasEscapes(pdus []tpdu.TPDU) bool {
	for _, pdu := range pdus {
		for _, d := range pdu.UD {
			if d == 0x1b {
				return true
			}
		}
	}
	return false
}

func usage(fs *flag.FlagSet) {
	_, _ = fmt.Fprintf(fs.Output(), "smscounter determines the number of SMS-Submit TPDUs "+
		"required to encode a given message.\n"+
		"The message is encoded using the GSM7 default alphabet, or if necessary\n"+
		"an optionally specified character set, or failing those as UCS-2.\n"+
		"If the message is too long for a single PDU then it is split into several.\n\n"+
		"Usage: smscounter -message <message> [-language <nli>]\n")
	fs.PrintDefaults()
}

// Count contains the statistics related to encoding a message in SMS-SUBMIT TPDUs.
type Count struct {
	Encoding  string
	Messages  int
	Tlen      int
	Llen      int
	Pdulen    int
	Remaining int
}

func (c Count) String() string {
	return fmt.Sprintf("encoding: %s\n", c.Encoding) +
		fmt.Sprintf("messages: %d\n", c.Messages) +
		fmt.Sprintf("total length: %d\n", c.Tlen) +
		fmt.Sprintf("last PDU length: %d\n", c.Llen) +
		fmt.Sprintf("per_message: %d\n", c.Pdulen) +
		fmt.Sprintf("remaining: %d\n", c.Remaining)
}
